# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    # Security
    - gosec
    - bodyclose
    
    # Bugs
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - typecheck
    
    # Style
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    
    # Complexity
    - gocyclo
    - gocognit
    
    # Performance
    - prealloc

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - (io.Closer).Close
      - (net/http.ResponseWriter).Write

  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G104 # Audit errors not checked (we handle this case by case)

  gocyclo:
    min-complexity: 20

  gocognit:
    min-complexity: 30

  misspell:
    locale: US

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/kirin2461/Nemaxks

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - gosec
        - gocognit

    # Exclude known issues in generated files
    - path: "\\.pb\\.go"
      linters:
        - all

  max-issues-per-linter: 50
  max-same-issues: 10

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
